sudo: required

dist: trusty

language: node_js

node_js:
  - '18'
install:
  - npm install -g yarn
  - yarn
env:
  - TASK=test
matrix:
  fast_finish: true
  allow_failures:
before_script:
  - ganache-cli > /dev/null &
  - sleep 5
script:
  - yarn $TASK

notifications:
  email: false
